---

name: CI pipeline for mpi-pytest

on:
  push:
  pull_request:
  schedule:
    - cron: '1 5 * * 1'

jobs:

  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python: ['3.9', '3.10', '3.11', '3.12', '3.13']
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Conda environment with Micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: "etc/test_environment_mpich.yml"
          create-args: >-
              python=${{ matrix.python }}
      - name: Install mpi-pytest as a package in the current environment
        run: |
          pip install --no-deps -e .
      - name: Run tests
        run: |
          pytest --continue-on-collection-errors -v tests
